language: go
go:
- 1.3

install:
- go get code.google.com/p/go.tools/cmd/vet

script:
  - go get -d -v ./...
  - go build -v ./...
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
