language: go
go:
- 1.4

install:
- DST=~/gopath/src/github.com/nats-io
- mkdir -p "$DST"
- git clone --depth=1 --quiet https://github.com/nats-io/gnatsd.git "$DST"/gnatsd
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
  - go get -d -v ./...
  - go build -v ./...
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - GOMAXPROCS=1 go test -v -race ./...
  - GOMAXPROCS=1 go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile coverage.out -service travis-ci
